name: Generate Image Manifests

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Show workspace structure
        run: ls -R .
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Generate manifests
        run: node scripts/generate-manifests.js
      - name: Commit manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/**/manifest.json
          git diff --quiet && echo "No changes" || git commit -m "chore: update image manifests"
          git push
