name: Generate Image Manifests

on:
  push:
    paths:
      - 'images/**'      # Nur auslösen, wenn sich in images/ etwas ändert
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Generate manifests
        run: |
          npm install
          node scripts/generate-manifests.js
      - name: Commit manifests
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add images/**/manifest.json
          git diff --quiet && echo "No changes" || git commit -m "chore: update image manifests"
          git push
